# --> check the first Py file
- src/data_interactivity_activity.ipynb:
    - description: Ensure that the file src/data_interactivity_activity.ipynb exists
      check: ConfirmFileExists
    - description: Complete all TODOs and remove the TODO markers in the file src/storyProblem.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the file src/storyProblem.py
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true

# --> check that the number of commits in the Git repository is beyond a threshold
- description: Have at least a specific minimum number of commits (3) in repository
  check: CountCommits
  options:
    count: 3
